services:
  - type: web
    name: restaurant-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_PATH
        value: uploads/
      - key: MAX_FILE_SIZE
        value: 5242880

databases:
  - name: restaurant-db
    databaseName: restaurant_db
    user: restaurant_user